import Head from 'next/head'
import About from '../components/About'
import Contact from '../components/Contact'
import Hero from '../components/Hero'
import Skills from '../components/Skills'
import Work from '../components/Work'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nicholas Mutale Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <About />
      <Skills />
      <Work />
      <Contact />   
    </div>
  )
}
